# .github/workflows/node.js.yml

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build static site
      run: npm run build
      # Соберет статику в папку out/ (т.к. у тебя output: 'export')
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: static-site
        path: out/
      # Сохранит собранную статику как артефакт (можно скачать)
